### ISSUE TITLE
Cannot start container in master replication mode

### ISSUE THREAD

**Issue by mkorz** [bitnami/bitnami-docker-redis#122] opened 2018-11-02 10:13 UTC
**Description**
Attempt to run container as replication master causes it to **silently exit** on startup. This worked ok in  previous builds.

**Steps to reproduce the issue:**
1.  Start the container with REDIS_REPLICATION_MODE=master: 
``docker run --rm -it -e REDIS_REPLICATION_MODE=master -e ALLOW_EMPTY_PASSWORD=yes bitnami/redis:4.0.11-ol-7-r92``
1. Container will exit with status code 1

**Describe the results you received:**
Output from container:
```
Welcome to the Bitnami redis container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-redis
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-redis/issues
Send us your feedback at containers@bitnami.com

INFO  ==> ** Starting Redis setup **
WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
INFO  ==> Initializing Redis...
INFO  ==> Configuring replication mode...
```

**Describe the results you expected:**
Running container :)
Previous build works:
``docker run --rm -it -e REDIS_REPLICATION_MODE=master -e ALLOW_EMPTY_PASSWORD=yes bitnami/redis:4.0.11-ol-7-r91``

Previous build output:
```
Welcome to the Bitnami redis container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-redis
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-redis/issues
Send us your feedback at containers@bitnami.com

WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
1:C 02 Nov 10:01:43.648 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 02 Nov 10:01:43.648 # Redis version=4.0.11, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 02 Nov 10:01:43.648 # Configuration loaded
                _._
           _.-``__ ''-._
      _.-``    `.  `_.  ''-._           Redis 4.0.11 (00000000/0) 64 bit
  .-`` .-```.  ```\/    _.,_ ''-._
 (    '      ,       .-`  | `,    )     Running in standalone mode
 |`-._`-...-` __...-.``-._|'` _.-'|     Port: 6379
 |    `-._   `._    /     _.-'    |     PID: 1
  `-._    `-._  `-./  _.-'    _.-'
 |`-._`-._    `-.__.-'    _.-'_.-'|
 |    `-._`-._        _.-'_.-'    |           http://redis.io
  `-._    `-._`-.__.-'_.-'    _.-'
 |`-._`-._    `-.__.-'    _.-'_.-'|
 |    `-._`-._        _.-'_.-'    |
  `-._    `-._`-.__.-'_.-'    _.-'
      `-._    `-.__.-'    _.-'
          `-._        _.-'
              `-.__.-'

1:M 02 Nov 10:01:43.651 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
1:M 02 Nov 10:01:43.651 # Server initialized
1:M 02 Nov 10:01:43.651 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
1:M 02 Nov 10:01:43.651 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
1:M 02 Nov 10:01:43.651 * Ready to accept connections
```
**Additional information you deem important (e.g. issue happens only occasionally):**

Same behaviour is experienced with debian 9 based chart (4.0.11-debian-9-r82 crashes, whilst 4.0.11-debian-9-r81 works).

**Version**

- Output of `docker version`:

```
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:17:20 2018
 OS/Arch:      linux/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:15:30 2018
  OS/Arch:      linux/amd64
  Experimental: false
```

- Output of `docker info`:
```
Containers: 10
 Running: 8
 Paused: 0
 Stopped: 2
Images: 84
Server Version: 18.03.1-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 306
 Dirperm1 Supported: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 3.13.0-71-generic
Operating System: Ubuntu 16.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 23.44GiB
Name: docker
ID: CUI4:XN4I:V6MD:5TYD:FP7S:ETN4:JC3E:LZXH:ESD7:R4AI:5XU7:45DU
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details:**
I was also able to reproduce this issue on GKE by installing bitnami redis helm chart.

**Comment by tjerkw** [comment] 2018-11-02 10:54
We also start having this issue.
```

[tiqetsweb-redis-master-0]
[tiqetsweb-redis-master-0] Welcome to the Bitnami redis container
[tiqetsweb-redis-master-0] Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-redis
[tiqetsweb-redis-master-0] Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-redis/issues
[tiqetsweb-redis-master-0] Send us your feedback at containers@bitnami.com
[tiqetsweb-redis-master-0]
[tiqetsweb-redis-master-0] INFO  ==> ** Starting Redis setup **
[tiqetsweb-redis-master-0] WARN  ==> You set the environment variable ALLOW_EMPTY_PASSWORD=yes. For safety reasons, do not use this flag in a production environment.
[tiqetsweb-redis-master-0] INFO  ==> Initializing Redis...
[tiqetsweb-redis-master-0] INFO  ==> Configuring replication mode...

```

**Comment by tjerkw** [comment] 2018-11-02 10:55
Based on image:  pulling image "docker.io/bitnami/redis:4.0.11-debian-9"

**Comment by amir-hadi** [comment] 2018-11-02 12:15
Same here. Did someone already identify a workaround?

**Comment by mkorz** [comment] 2018-11-02 12:41
4.0.11-ol-7-r91 and 4.0.11-debian-9-r81 both works for me.
As for the helm chart, install/upgrade with sth like: ``--set redis.image.tag=4.0.11-debian-9-r81``

**Comment by javsalgar** [comment] 2018-11-02 13:05
I was able to reproduce it. There must be something incorrect when setting the replication, as the entrypoint command is exiting with a non-zero status. We'll take a look at it

**Comment by javsalgar** [comment] 2018-11-02 13:07
Ok, I see that it fails because of the ALLOW_EMPTY_PASSWORD variable. I am not 100% sure if replication with empty password is currently supported in the container. If you set the REDIS_PASSWORD variable it works. 

cc @andresbono @juan131

**Comment by juan131** [comment] 2018-11-02 14:12
Thanks for reporting!! We include some code refactoring in the last revision. I'm taking a look and I'll release a new revision as soon as we have a fix. Sorry for the inconveniences!

**Comment by mkorz** [comment] 2018-11-02 14:33
Thanks for looking into it!
I actually encountered it in a scenario of running minimal throwaway redis setup via Bitnami helm chart - with single master and no slaves, using following values:
```
redis:
  usePassword: false
  cluster:
    enabled: false
  master:
    persistence:
      enabled: false
```
Probably helm chart could be improved to skip setting *REDIS_REPLICATION_MODE* when `cluster.enabled` is false.

**Comment by juan131** [comment] 2018-11-02 14:47
I just released new images fixing this issue. Could you try with one of the following images?

- **5.0.0-debian-9-r4** 
- **4.0.11-debian-9-r83**
- **5.0.0-ol-7-r4**
- ** 4.0.11-ol-7-r93**

**Comment by nphmuller** [comment] 2018-11-02 14:53
Works with the helm chart config @mkorz posted!

**Comment by AlecTroemel** [comment] 2018-11-02 14:58
was experiencing this issue, @juan131 image `4.0.11-debian-9-r83` image fixed it for me.

**Comment by juan131** [comment] 2018-11-02 15:12
Great!!! Did it solve your issues too @mkorz @tjerkw @msta @amir-hadi ?

**Comment by juan131** [comment] 2018-11-02 15:36
Hi @AlecTroemel 

Here you can find the reason for this wrong behaviour: https://github.com/bitnami/bitnami-docker-redis/blob/master/4.0/debian-9/rootfs/libredis.sh#L237

Instead of:

```
if is_boolean_yes "$ALLOW_EMPTY_PASSWORD" && [[ -z "$REDIS_MASTER_PASSWORD" ]]; then
  empty_password_error REDIS_MASTER_PASSWORD
...
```

It should be:

```
if ! is_boolean_yes "$ALLOW_EMPTY_PASSWORD" && [[ -z "$REDIS_MASTER_PASSWORD" ]]; then
  empty_password_error REDIS_MASTER_PASSWORD
...
```

Working on the fix! Thanks for reporting it!

**Comment by juan131** [comment] 2018-11-02 15:57
New images released addressing these issues:

- **5.0.0-debian-9-r5**
- **4.0.11-debian-9-r84**
- **5.0.0-ol-7-r5**
- **4.0.11-ol-7-r94**

Sorry again for the inconveniences! 

We did a huge code refactoring to make easier users to contribute to the Bash scripts we use to initialise the servers/applications. We want to do these scripts as descriptive and easy to follow as possible so everyone understands what's going on.

**Comment by mkorz** [comment] 2018-11-02 17:50
Both 4.0.11-debian-9-r83 and 4.0.11-debian-9-r84 works for me.
Thank you @juan131 - top stuff! Much appreciated!

**Comment by AlecTroemel** [comment] 2018-11-04 16:51
+1 to the thank you @juan131, super quick fix!

**Comment by juan131** [comment] 2018-11-05 08:19
I'm very glad to hear the last images fixed the issue!! 

I'm closing this issue, please feel free to reopen it in case you face issues with **ALLOW_EMPTY_PASSWORD** env. variable again

**Closed by juan131** 2018-11-05 08:19 UTC
